ag_starts_homepage:
    resource: "@AGStartsBundle/Controller/DefaultController.php"
    type:     annotation

ag_starts_auth:
    resource: "@AGStartsBundle/Controller/AuthController.php"
    type:     annotation

